/** Writes db/seeds/stage_definitions.sql from @nk/stage-config so the DB and the apps share one definition. */
import { writeFileSync } from 'node:fs';
import { CROPS } from '../packages/shared/src';
import { defaultStages } from '../packages/stage-config/src';

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const rows = CROPS.flatMap((c) =>
  defaultStages(c.code).map((s) =>
    `  (${q(c.code)}, ${q(s.stageCode)}, ${q(s.name)}, ${s.sequence}, ${q(s.appliesToParent)}, ${s.repeatable}, ${s.mandatory}, ${s.expectedDayOffset}, ${s.minPhotos > 0}, ${s.minPhotos}, ${s.requiresGeofence}, ${q(JSON.stringify(s.fields))}::jsonb)`,
  ),
);
const sql = `-- Generated by scripts/gen-stage-seed.ts. Do not edit by hand.
INSERT INTO stage_definition (crop_code, stage_code, name, sequence, applies_to_parent, repeatable, mandatory, expected_day_offset, requires_photo, min_photos, requires_geofence, form_schema) VALUES
${rows.join(',\n')}
ON CONFLICT (crop_code, stage_code) DO NOTHING;
`;
writeFileSync(new URL('../db/seeds/stage_definitions.sql', import.meta.url), sql);
console.log(`Wrote ${rows.length} stage definitions`);
